name: Build and Publish

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      dockerhub-username:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: ${{ inputs.project-directory }}
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --file ${{ inputs.dockerfile-path }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project-directory }}:latest .
