name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:

  build-and-publish-backend:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      project-directory: quarkus-affirmations-backend

  build-and-publish-frontend:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      project-directory: quarkus-affirmations-frontend
